### PR TITLE
Hotfix/1.0.4

### LINKED ISSUE #235: the continue button on the main menu doesn't do anything
played through hop 1 and 2. on hop 2 i clicked go back to main menu. continue still doesn't work on the main menu

### LINKED ISSUE #237: using the restart level shortcut(t) on the finished level menu doesn't restart the level.
but (r) does. should make it so you can press either or to restart the level on the completion of a level

### LINKED ISSUE #238: hop14: on your first spawn you spawn outside of the spawning area in midair

### LINKED ISSUE #239: the background image for main menu and level editor is different. the level editor 1 is squished
level editor
bild
main menu
bild

### LINKED ISSUE #240: some settings in the options menu doesn't set themself correctly on load.
including but not limited to

fullscreen,resolution

all the toggles in misc except ghost and console toggle

audio levels
got a video of it. its in #jjdev message me if u cant  find it.

### LINKED ISSUE #243: Add back in pre-strafing

### LINKED ISSUE #245: Clipping on walls should slow you down, instead you can gain infinite speed

### LINKED ISSUE #246: Hop3 bone times

### LINKED ISSUE #248: Add vsync option

### PR DESCRIPTION
**Pull request by ambid17**
Closes #248 
Closes #243 
Closes #246 
Closes #245 
Closes #239 
Closes #238 
Closes #237 
Closes #240

### CODE REVIEW

File: Assets/Scripts/UI/SettingsMenu/VideoOptions.cs [hunk 1]
```diff
@@ -50,61 +56,59 @@ void SetupResolutionDropdown()
...
         {
-            GameObject newDropdown = Instantiate(dropdownItemPrefab, scrollViewContent);
-            fullScreenDropdown = newDropdown.GetComponent<DropdownItem>();
+            GameObject newToggle = Instantiate(togglePrefab, scrollViewContent);
+            vsyncToggle = newToggle.GetComponent<ToggleItem>();
         }
-        fullScreenDropdown.Init("Fullscreen", 0, new List<string> {"FullScreen", "Windowed"}, SetFullScreen, PlayerConstants.FullscreenTooltip);
+
+        int startValue = OptionsPreferencesManager.GetVsync();
+        bool isToggled = startValue == 1 ? true : false;
```
Comment (maxwellpark) [inline Assets/Scripts/UI/SettingsMenu/VideoOptions.cs:106]: could do `isToggled = startValue != 0;` for brevity

File: Assets/Scripts/UI/SettingsMenu/OptionsPreferencesManager.cs [hunk 2]
```diff
@@ -2,33 +2,40 @@
...
 
+    #region Audio
     public const string musicVolumeKey = "Volume";
     public const int defaultMusicVolume = -20;
 
     public const string soundEffectVolumeKey = "SoundEffects";
     public const int defaultSoundEffectVolume = -80;
+    #endregion
+
+    #region Video
```
Comment (maxwellpark) [inline Assets/Scripts/UI/SettingsMenu/OptionsPreferencesManager.cs:18]: yo dawg, I heard u like regions, :D
